apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvghj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cvghj
  template:
    metadata:
      labels:
        app: cvghj
    spec:
      containers:
      - image: okteto.dev/cvghj:latest
        name: cvghj
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "8da55dc2-e4c9-4529-8a88-2a797b591419"
        - name: Vless_Path
          value: "/vl5gfh55"
        - name: Vmess_UUID
          value: "8da55dc2-e4c9-4529-8a88-2a797b591419"
        - name: Vmess_Path
          value: "/vm6jhk6"
        - name: Share_Path
          value: "/v2link"
